#!/usr/bin/env bash
set -euo pipefail
CONNECT="sys/${ORACLE_PASSWORD}@//localhost:1521/FREEPDB1 as sysdba"
sqlplus -s "$CONNECT" <<SQL
WHENEVER SQLERROR EXIT SQL.SQLCODE
BEGIN
  FOR r IN (SELECT username FROM dba_users WHERE username IN (
    'SALUDABLEMENTE_OWNER','SLB_PERSONAL','SLB_APTITUDFISICA','SLB_NUTRICIONAL','SALUD_PERSONAL',
    'SALUD_ALERTA_CLINICA','SALUD_AUDITORIA','SALUD_EXPORTACION','SALUD_PERFIL_REPORTE','SALUD_RECOMENDACIONES_IA')) LOOP
    FOR t IN (SELECT table_name FROM dba_tables WHERE owner = r.username) LOOP
      EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ' || r.username || '.' || t.table_name || ' TO ${APP_USER}';
    END LOOP;
  END LOOP;
  EXECUTE IMMEDIATE 'GRANT SELECT ON SALUD_ALERTA_CLINICA.SEQ_ACCION_CORRECTIVA TO ${APP_USER}';
END;
/
EXIT
SQL
