-- =====================================================
-- MODULO: AUDITORIA
-- Esquema: SALUD_AUDITORIA
-- Sin FK a PERSONA (aislamiento de modulos - BOM ERP)
-- =====================================================

-- =====================================================
-- TABLA: BITACORA_TRANSACCIONAL
-- Particionada por rango mensual. Solo INSERT (WORM).
-- =====================================================
CREATE TABLE BITACORA_TRANSACCIONAL (
    ID_BITACORA RAW(16) DEFAULT SYS_GUID() NOT NULL,
    SECUENCIA NUMBER(19) NOT NULL,
    TIPO_EVENTO VARCHAR2(80) NOT NULL,
    ENTIDAD_AFECTADA VARCHAR2(50) NOT NULL,
    ID_ENTIDAD VARCHAR2(100) NOT NULL,
    TIPO_OPERACION VARCHAR2(20) NOT NULL,
    ID_PERSONA NUMBER(10),
    USUARIO_AUTOR VARCHAR2(100) NOT NULL,
    ROL_USUARIO VARCHAR2(100),
    TENANT_ID VARCHAR2(50),
    DIFERENCIAL_CAMBIOS CLOB,
    SNAPSHOT_ANTERIOR CLOB,
    SNAPSHOT_POSTERIOR CLOB,
    DIRECCION_IP VARCHAR2(45),
    PUERTO_REMOTO VARCHAR2(10),
    USER_AGENT VARCHAR2(255),
    ENDPOINT_HTTP VARCHAR2(200),
    METODO_HTTP VARCHAR2(10),
    CODIGO_RESPUESTA_HTTP NUMBER(3),
    HASH_REGISTRO VARCHAR2(64) NOT NULL,
    HASH_ANTERIOR VARCHAR2(64),
    FUERA_HORARIO_LABORAL VARCHAR2(1),
    FECHA_REGISTRO TIMESTAMP NOT NULL,
    CONSTRAINT PK_BITACORA_TRANSACCIONAL PRIMARY KEY (ID_BITACORA, FECHA_REGISTRO),
    CONSTRAINT CK_BITACORA_FUERA_HORARIO CHECK (FUERA_HORARIO_LABORAL IN ('S', 'N'))
)
PARTITION BY RANGE (FECHA_REGISTRO)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P_INICIAL VALUES LESS THAN (TO_DATE('2026-01-01', 'YYYY-MM-DD'))
);

CREATE UNIQUE INDEX IDX_BITACORA_SECUENCIA ON BITACORA_TRANSACCIONAL(SECUENCIA);
CREATE INDEX IDX_BITACORA_ENTIDAD ON BITACORA_TRANSACCIONAL(ENTIDAD_AFECTADA, ID_ENTIDAD) LOCAL;
CREATE INDEX IDX_BITACORA_HASH_ANT ON BITACORA_TRANSACCIONAL(HASH_ANTERIOR) LOCAL;
CREATE INDEX IDX_BITACORA_USUARIO ON BITACORA_TRANSACCIONAL(USUARIO_AUTOR) LOCAL;
CREATE INDEX IDX_BITACORA_PERSONA ON BITACORA_TRANSACCIONAL(ID_PERSONA) LOCAL;

-- =====================================================
-- TABLA: BITACORA_LECTURA
-- Particionada por rango mensual.
-- =====================================================
CREATE TABLE BITACORA_LECTURA (
    ID_LECTURA RAW(16) DEFAULT SYS_GUID() NOT NULL,
    ID_PERSONA NUMBER(10) NOT NULL,
    TIPO_ENTIDAD VARCHAR2(50) NOT NULL,
    ID_ENTIDAD VARCHAR2(100) NOT NULL,
    USUARIO_LECTOR VARCHAR2(100) NOT NULL,
    DIRECCION_IP VARCHAR2(45),
    USER_AGENT VARCHAR2(255),
    FECHA_ACCESO TIMESTAMP NOT NULL,
    CONSTRAINT PK_BITACORA_LECTURA PRIMARY KEY (ID_LECTURA, FECHA_ACCESO)
)
PARTITION BY RANGE (FECHA_ACCESO)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P_INICIAL VALUES LESS THAN (TO_DATE('2026-01-01', 'YYYY-MM-DD'))
);

CREATE INDEX IDX_LECTURA_PERSONA ON BITACORA_LECTURA(ID_PERSONA) LOCAL;
CREATE INDEX IDX_LECTURA_USUARIO ON BITACORA_LECTURA(USUARIO_LECTOR) LOCAL;

-- =====================================================
-- TABLA: EVENTO_AUDITORIA_DLQ
-- =====================================================
CREATE TABLE EVENTO_AUDITORIA_DLQ (
    ID_FALLO RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    TIPO_EVENTO VARCHAR2(80) NOT NULL,
    PAYLOAD_EVENTO CLOB NOT NULL,
    TIPO_ERROR VARCHAR2(120) NOT NULL,
    MENSAJE_ERROR VARCHAR2(500),
    ESTADO VARCHAR2(30) NOT NULL,
    INTENTOS_REINTENTO NUMBER(5) DEFAULT 0 NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_ULTIMO_INTENTO TIMESTAMP,
    CONSTRAINT CK_DLQ_ESTADO CHECK (ESTADO IN (
        'PENDIENTE_REINTENTO', 'PROCESANDO', 'FALLIDO_DEFINITIVO', 'RESUELTO'))
);

CREATE INDEX IDX_DLQ_ESTADO ON EVENTO_AUDITORIA_DLQ(ESTADO);
CREATE INDEX IDX_DLQ_FECHA ON EVENTO_AUDITORIA_DLQ(FECHA_REGISTRO);

-- =====================================================
-- TABLA: BITACORA_SEGURIDAD
-- =====================================================
CREATE TABLE BITACORA_SEGURIDAD (
    ID_ALERTA RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USUARIO_AFECTADO VARCHAR2(100),
    TIPO_ANOMALIA VARCHAR2(50) NOT NULL,
    SEVERIDAD VARCHAR2(20) NOT NULL,
    METADATA_CONTEXTO CLOB,
    ESTADO_ALERTA VARCHAR2(30) DEFAULT 'NO_RESUELTA' NOT NULL,
    FECHA_DETECCION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_RESOLUCION TIMESTAMP,
    RESUELTO_POR VARCHAR2(100),
    OBSERVACIONES VARCHAR2(500),
    CONSTRAINT CK_SEGURIDAD_TIPO_ANOMALIA CHECK (TIPO_ANOMALIA IN (
        'IMPOSSIBLE_TRAVEL', 'RATE_LIMIT_EXCEEDED', 'UNAUTHORIZED_ACCESS',
        'BREAK_GLASS_ACCESS', 'PROMPT_INJECTION', 'MASSIVE_DOWNLOAD',
        'OUT_OF_HOURS_MODIFICATION', 'SUSPICIOUS_LOGIN_PATTERN')),
    CONSTRAINT CK_SEGURIDAD_SEVERIDAD CHECK (SEVERIDAD IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT CK_SEGURIDAD_ESTADO CHECK (ESTADO_ALERTA IN (
        'NO_RESUELTA', 'EN_INVESTIGACION', 'RESUELTA', 'FALSO_POSITIVO'))
);

CREATE INDEX IDX_SEGURIDAD_TIPO ON BITACORA_SEGURIDAD(TIPO_ANOMALIA);
CREATE INDEX IDX_SEGURIDAD_FECHA ON BITACORA_SEGURIDAD(FECHA_DETECCION);
CREATE INDEX IDX_SEGURIDAD_ESTADO ON BITACORA_SEGURIDAD(ESTADO_ALERTA);
CREATE INDEX IDX_SEGURIDAD_USUARIO ON BITACORA_SEGURIDAD(USUARIO_AFECTADO);

-- =====================================================
-- TABLA: SESION_USUARIO
-- =====================================================
CREATE TABLE SESION_USUARIO (
    ID_SESION RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USUARIO VARCHAR2(100) NOT NULL,
    DIRECCION_IP VARCHAR2(45) NOT NULL,
    CIUDAD VARCHAR2(100),
    PAIS VARCHAR2(100),
    CODIGO_PAIS VARCHAR2(5),
    LATITUD BINARY_DOUBLE,
    LONGITUD BINARY_DOUBLE,
    USER_AGENT VARCHAR2(255),
    FECHA_LOGIN TIMESTAMP NOT NULL,
    SESION_ACTIVA VARCHAR2(1) DEFAULT 'S',
    CONSTRAINT CK_SESION_ACTIVA CHECK (SESION_ACTIVA IN ('S', 'N'))
);

CREATE INDEX IDX_SESION_USUARIO_FECHA ON SESION_USUARIO(USUARIO, FECHA_LOGIN);
CREATE INDEX IDX_SESION_IP ON SESION_USUARIO(DIRECCION_IP);

-- =====================================================
-- TABLA: MANIFIESTO_ARCHIVADO_FRIO
-- =====================================================
CREATE TABLE MANIFIESTO_ARCHIVADO_FRIO (
    ID_MANIFIESTO RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    RANGO_FECHA_INICIO TIMESTAMP NOT NULL,
    RANGO_FECHA_FIN TIMESTAMP NOT NULL,
    TOTAL_REGISTROS_EXPORTADOS NUMBER(12) NOT NULL,
    RUTA_COLD_STORAGE VARCHAR2(300) NOT NULL,
    TAMANO_ARCHIVO_BYTES NUMBER(19) NOT NULL,
    HASH_MANIFIESTO VARCHAR2(64) NOT NULL,
    FIRMA_RSA VARCHAR2(1000),
    FECHA_EXPORTACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    RESPONSABLE_PURGA VARCHAR2(100) NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'GENERADO' NOT NULL,
    FECHA_PURGA TIMESTAMP,
    CONSTRAINT CK_MANIFIESTO_ESTADO CHECK (ESTADO IN ('GENERADO', 'ARCHIVADO', 'PURGADO'))
);

CREATE INDEX IDX_MANIFIESTO_ESTADO ON MANIFIESTO_ARCHIVADO_FRIO(ESTADO);
CREATE INDEX IDX_MANIFIESTO_RANGO ON MANIFIESTO_ARCHIVADO_FRIO(RANGO_FECHA_INICIO, RANGO_FECHA_FIN);

-- =====================================================
-- TABLA: PARTICION_BITACORA
-- =====================================================
CREATE TABLE PARTICION_BITACORA (
    ID_PARTICION RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NOMBRE_PARTICION VARCHAR2(100) NOT NULL UNIQUE,
    TABLA_ORIGEN VARCHAR2(60) NOT NULL,
    RANGO_FECHA_INICIO TIMESTAMP NOT NULL,
    RANGO_FECHA_FIN TIMESTAMP NOT NULL,
    TOTAL_REGISTROS NUMBER(12),
    TAMANO_BYTES NUMBER(19),
    ESTADO VARCHAR2(30) DEFAULT 'ACTIVA' NOT NULL,
    ARCHIVADA VARCHAR2(1) DEFAULT 'N',
    PURGADA VARCHAR2(1) DEFAULT 'N',
    ID_MANIFIESTO RAW(16),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CK_PARTICION_ARCHIVADA CHECK (ARCHIVADA IN ('S', 'N')),
    CONSTRAINT CK_PARTICION_PURGADA CHECK (PURGADA IN ('S', 'N')),
    CONSTRAINT FK_PARTICION_MANIFIESTO FOREIGN KEY (ID_MANIFIESTO)
        REFERENCES MANIFIESTO_ARCHIVADO_FRIO(ID_MANIFIESTO)
);

CREATE INDEX IDX_PARTICION_TABLA ON PARTICION_BITACORA(TABLA_ORIGEN);
CREATE INDEX IDX_PARTICION_ARCHIVADA ON PARTICION_BITACORA(ARCHIVADA);
CREATE INDEX IDX_PARTICION_PURGADA ON PARTICION_BITACORA(PURGADA);

-- =====================================================
-- TABLA: POLITICA_RETENCION
-- =====================================================
CREATE TABLE POLITICA_RETENCION (
    ID_POLITICA RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    TIPO_DATO VARCHAR2(40) NOT NULL UNIQUE,
    DIAS_RETENCION_CALIENTE NUMBER(5) NOT NULL,
    MESES_RETENCION_FRIO NUMBER(4) NOT NULL,
    ANIOS_RETENCION_LEGAL NUMBER(3) NOT NULL,
    PURGA_AUTOMATICA VARCHAR2(1) DEFAULT 'S',
    ACTIVA VARCHAR2(1) DEFAULT 'S',
    DESCRIPCION VARCHAR2(300),
    CONSTRAINT CK_POLITICA_PURGA CHECK (PURGA_AUTOMATICA IN ('S', 'N')),
    CONSTRAINT CK_POLITICA_ACTIVA CHECK (ACTIVA IN ('S', 'N'))
);

-- Datos iniciales
INSERT INTO POLITICA_RETENCION (ID_POLITICA, TIPO_DATO, DIAS_RETENCION_CALIENTE,
                                 MESES_RETENCION_FRIO, ANIOS_RETENCION_LEGAL, DESCRIPCION)
VALUES (SYS_GUID(), 'DATOS_MEDICOS', 365, 60, 5, 'Datos clinicos y de salud ocupacional');

INSERT INTO POLITICA_RETENCION (ID_POLITICA, TIPO_DATO, DIAS_RETENCION_CALIENTE,
                                 MESES_RETENCION_FRIO, ANIOS_RETENCION_LEGAL, DESCRIPCION)
VALUES (SYS_GUID(), 'LOGS_TECNICOS', 365, 12, 1, 'Logs tecnicos y de aplicacion');

INSERT INTO POLITICA_RETENCION (ID_POLITICA, TIPO_DATO, DIAS_RETENCION_CALIENTE,
                                 MESES_RETENCION_FRIO, ANIOS_RETENCION_LEGAL, DESCRIPCION)
VALUES (SYS_GUID(), 'ACCESOS_LECTURA', 365, 60, 5, 'Registro de lecturas de datos sensibles');

-- =====================================================
-- TRIGGER WORM: prohibe UPDATE y DELETE en bitacora
-- =====================================================
CREATE OR REPLACE TRIGGER TRG_BITACORA_WORM
BEFORE UPDATE OR DELETE ON BITACORA_TRANSACCIONAL
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001,
        'BITACORA_TRANSACCIONAL es WORM (Write Once Read Many). No se permite UPDATE ni DELETE.');
END;
/

CREATE OR REPLACE TRIGGER TRG_BITACORA_LECTURA_WORM
BEFORE UPDATE OR DELETE ON BITACORA_LECTURA
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20002,
        'BITACORA_LECTURA es WORM. No se permite UPDATE ni DELETE.');
END;
/

COMMIT;
