-- =====================================================
-- MODULO: EXPORTACION / INTEROPERABILIDAD
-- Esquema: SALUD_EXPORTACION
-- Sin FK a PERSONA (aislamiento de modulos - BOM ERP)
-- =====================================================

-- =====================================================
-- TABLA: TAREA_EXPORTACION
-- Cola persistente de trabajos de exportación (síncronos y asíncronos)
-- =====================================================
CREATE TABLE TAREA_EXPORTACION (
    ID_TAREA RAW(16) DEFAULT SYS_GUID() NOT NULL,
    ID_USUARIO_SOLICITANTE NUMBER(10) NOT NULL,
    TITULO_LOTE VARCHAR2(150) NOT NULL,
    ESTADO_TAREA VARCHAR2(20) DEFAULT 'EN_COLA' NOT NULL,
    FORMATO_SALIDA VARCHAR2(30) NOT NULL,
    MODO_PRIVACIDAD VARCHAR2(30) NOT NULL,
    PARAMETROS_FILTRO CLOB NOT NULL,
    PORCENTAJE_AVANCE NUMBER(3) DEFAULT 0 NOT NULL,
    FASE_ACTUAL VARCHAR2(30),
    TOTAL_REGISTROS_ESTIMADOS NUMBER(10),
    TOTAL_REGISTROS_PROCESADOS NUMBER(10),
    RUTA_ALMACENAMIENTO VARCHAR2(300),
    TAMANO_BYTES NUMBER(19),
    HASH_SHA256 VARCHAR2(64),
    ESTA_CIFRADO VARCHAR2(1) DEFAULT 'N' NOT NULL,
    FECHA_SOLICITUD TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_INICIO_PROCESO TIMESTAMP,
    FECHA_FINALIZACION TIMESTAMP,
    MENSAJE_ERROR CLOB,
    CONSTRAINT PK_TAREA_EXPORTACION PRIMARY KEY (ID_TAREA),
    CONSTRAINT CK_TAREA_ESTADO CHECK (ESTADO_TAREA IN (
        'EN_COLA', 'PROCESANDO', 'COMPLETADO', 'FALLIDO', 'CANCELADO')),
    CONSTRAINT CK_TAREA_FORMATO CHECK (FORMATO_SALIDA IN (
        'MS_EXCEL_XLSX', 'CSV_TABULAR', 'JSON_ESTRUCTURADO', 'HL7_FHIR_JSON',
        'APACHE_PARQUET', 'ZIP_EXPEDIENTES', 'PDF_CONSOLIDADO')),
    CONSTRAINT CK_TAREA_PRIVACIDAD CHECK (MODO_PRIVACIDAD IN (
        'COMPLETO_NOMINATIVO', 'PSEUDONIMIZADO', 'ANONIMIZADO_ESTADISTICO')),
    CONSTRAINT CK_TAREA_CIFRADO CHECK (ESTA_CIFRADO IN ('S', 'N')),
    CONSTRAINT CK_TAREA_AVANCE CHECK (PORCENTAJE_AVANCE BETWEEN 0 AND 100),
    CONSTRAINT CK_TAREA_FASE CHECK (FASE_ACTUAL IS NULL OR FASE_ACTUAL IN (
        'EXTRAYENDO_DATOS', 'APLICANDO_PRIVACIDAD', 'TRANSFORMANDO_FORMATO',
        'CIFRANDO', 'ALMACENANDO', 'FINALIZADO'))
);

CREATE INDEX IDX_TAREA_SOLICITANTE ON TAREA_EXPORTACION(ID_USUARIO_SOLICITANTE);
CREATE INDEX IDX_TAREA_ESTADO ON TAREA_EXPORTACION(ESTADO_TAREA);
CREATE INDEX IDX_TAREA_FECHA ON TAREA_EXPORTACION(FECHA_SOLICITUD);
CREATE INDEX IDX_TAREA_HASH ON TAREA_EXPORTACION(HASH_SHA256);

-- =====================================================
-- TABLA: BITACORA_DESCARGA_EXPORTACION
-- Trazabilidad local de cada descarga de paquete
-- =====================================================
CREATE TABLE BITACORA_DESCARGA_EXPORTACION (
    ID_DESCARGA RAW(16) DEFAULT SYS_GUID() NOT NULL,
    ID_TAREA RAW(16) NOT NULL,
    ID_USUARIO_DESCARGA NUMBER(10) NOT NULL,
    DIRECCION_IP VARCHAR2(45) NOT NULL,
    USER_AGENT VARCHAR2(255),
    FECHA_DESCARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_BITACORA_DESCARGA PRIMARY KEY (ID_DESCARGA),
    CONSTRAINT FK_DESCARGA_TAREA FOREIGN KEY (ID_TAREA)
        REFERENCES TAREA_EXPORTACION(ID_TAREA)
);

CREATE INDEX IDX_DESCARGA_TAREA ON BITACORA_DESCARGA_EXPORTACION(ID_TAREA);
CREATE INDEX IDX_DESCARGA_FECHA ON BITACORA_DESCARGA_EXPORTACION(FECHA_DESCARGA);

-- =====================================================
-- TABLA: SUSCRIPTOR_WEBHOOK
-- Sistemas externos suscritos a eventos de exportación
-- =====================================================
CREATE TABLE SUSCRIPTOR_WEBHOOK (
    ID_SUSCRIPTOR RAW(16) DEFAULT SYS_GUID() NOT NULL,
    NOMBRE_SISTEMA VARCHAR2(100) NOT NULL,
    URL_ENDPOINT VARCHAR2(300) NOT NULL,
    SECRETO_HMAC VARCHAR2(128) NOT NULL,
    EVENTOS_SUSCRITOS CLOB NOT NULL,
    ACTIVO VARCHAR2(1) DEFAULT 'S' NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_SUSCRIPTOR_WEBHOOK PRIMARY KEY (ID_SUSCRIPTOR),
    CONSTRAINT CK_SUSCRIPTOR_ACTIVO CHECK (ACTIVO IN ('S', 'N'))
);

CREATE INDEX IDX_SUSCRIPTOR_ACTIVO ON SUSCRIPTOR_WEBHOOK(ACTIVO);

-- =====================================================
-- TABLA: LOG_INTEROPERABILIDAD_FHIR
-- Trazabilidad de cada request FHIR externo
-- =====================================================
CREATE TABLE LOG_INTEROPERABILIDAD_FHIR (
    ID_LOG RAW(16) DEFAULT SYS_GUID() NOT NULL,
    ID_SISTEMA_CLIENTE VARCHAR2(100) NOT NULL,
    RECURSO_SOLICITADO VARCHAR2(50) NOT NULL,
    PARAMETROS_CONSULTA CLOB,
    CODIGO_HTTP_RESPUESTA NUMBER(3) NOT NULL,
    DIRECCION_IP VARCHAR2(45) NOT NULL,
    TIEMPO_RESPUESTA_MS NUMBER(10) NOT NULL,
    FECHA_PETICION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_LOG_FHIR PRIMARY KEY (ID_LOG),
    CONSTRAINT CK_FHIR_RECURSO CHECK (RECURSO_SOLICITADO IN (
        'Patient', 'Observation', 'Bundle', 'CapabilityStatement'))
);

CREATE INDEX IDX_FHIR_CLIENTE ON LOG_INTEROPERABILIDAD_FHIR(ID_SISTEMA_CLIENTE);
CREATE INDEX IDX_FHIR_RECURSO_FECHA
    ON LOG_INTEROPERABILIDAD_FHIR(RECURSO_SOLICITADO, FECHA_PETICION);

COMMIT;
