-- Local classroom development only. Execute once as SYSDBA after Oracle is healthy.
-- Credentials are intentionally aligned with the course setup and must be externalized before deployment.

CREATE USER SAL_TEAMS IDENTIFIED BY 123456
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO SAL_TEAMS;

CREATE USER SALUDABLEMENTE_APP IDENTIFIED BY 123456
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO SALUDABLEMENTE_APP;
