-- Execute as SAL_TEAMS after 01_provision_users.sql.
-- Logical-model mapping from saludablemente_schema.pdf:
-- TEAM.id_team -> SAL_TEAMS.TEAMS.ID
-- TEAM.nombre -> SAL_TEAMS.TEAMS.NAME
-- TEAM.descripcion -> SAL_TEAMS.TEAMS.DESCRIPTION
-- TEAM.activo -> SAL_TEAMS.TEAMS.ACTIVE (Oracle 0/1 boolean representation)
-- VARCHAR2 limits are intentionally wider than the logical minimum and do not
-- change the meaning of the shared attributes.

CREATE TABLE SAL_TEAMS.TEAMS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NAME VARCHAR2(100 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(500 CHAR),
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SAL_TEAMS_TEAMS PRIMARY KEY (ID),
    CONSTRAINT UK_SAL_TEAMS_TEAMS_NAME UNIQUE (NAME),
    CONSTRAINT CK_SAL_TEAMS_TEAMS_ACTIVE CHECK (ACTIVE IN (0, 1))
);

COMMENT ON TABLE SAL_TEAMS.TEAMS IS
    'Teams logical aggregate; owned by SAL_TEAMS and referenced by Personal through ID';
COMMENT ON COLUMN SAL_TEAMS.TEAMS.ID IS 'Logical id_team';
COMMENT ON COLUMN SAL_TEAMS.TEAMS.NAME IS 'Logical nombre';
COMMENT ON COLUMN SAL_TEAMS.TEAMS.DESCRIPTION IS 'Logical descripcion';
COMMENT ON COLUMN SAL_TEAMS.TEAMS.ACTIVE IS 'Logical activo: 1 active, 0 inactive';
