-- Execute as SAL_ACTIVITIES after 05_create_activities.sql.
-- Schema ownership remains in SAL_ACTIVITIES.

GRANT SELECT, INSERT, UPDATE ON SAL_ACTIVITIES.ACTIVITIES TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT ON SAL_ACTIVITIES.ACTIVITY_PLACE_LOCKS TO SALUDABLEMENTE_APP;
