-- S01_02_tablas.sql - Saludablemente (LP2 S1)
-- Ejecutar conectado como SYSTEM

CREATE TABLE SALUD_PERSONAL.TEAMS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE      VARCHAR2(60)  NOT NULL,
    DESCRIPCION VARCHAR2(200),
    ACTIVO      NUMBER(1)     DEFAULT 1 NOT NULL,
    CONSTRAINT UK_TEAM_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CK_TEAM_ACTIVO CHECK (ACTIVO IN (0, 1))
);

CREATE TABLE SALUD_PERSONAL.PERSONAS (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRES           VARCHAR2(80)  NOT NULL,
    APELLIDO_PATERNO  VARCHAR2(60)  NOT NULL,
    APELLIDO_MATERNO  VARCHAR2(60),
    AREA_TRABAJO      VARCHAR2(60),
    CELULAR           VARCHAR2(15)  NOT NULL,
    FECHA_NACIMIENTO  DATE          NOT NULL,
    TALLA_POLO        VARCHAR2(5),
    ESTADO_CIVIL      VARCHAR2(20),
    NIVEL_EDUCATIVO   VARCHAR2(30),
    SEXO              CHAR(1)       NOT NULL,
    ID_TEAM           NUMBER        NOT NULL,
    ACTIVO            NUMBER(1)     DEFAULT 1 NOT NULL,
    CONSTRAINT FK_PERSONA_TEAM FOREIGN KEY (ID_TEAM)
        REFERENCES SALUD_PERSONAL.TEAMS (ID),
    CONSTRAINT CK_PERSONA_SEXO CHECK (SEXO IN ('M', 'F')),
    CONSTRAINT CK_PERSONA_ACTIVO CHECK (ACTIVO IN (0, 1))
);

GRANT SELECT, INSERT, UPDATE, DELETE ON SALUD_PERSONAL.TEAMS TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SALUD_PERSONAL.PERSONAS TO SALUDABLEMENTE_APP;