-- Core synthetic data: Teams and Personal. Safe to re-run.
INSERT INTO SALUDABLEMENTE_OWNER.TEAMS (NAME, DESCRIPTION, ACTIVE)
SELECT 'DEMO-WELLNESS', 'Synthetic wellness team for local API demonstrations.', TRUE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM SALUDABLEMENTE_OWNER.TEAMS WHERE NAME = 'DEMO-WELLNESS');

INSERT INTO SLB_PERSONAL.PERSONA (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, CELULAR, FECHA_NACIMIENTO, SEXO, TALLA_POLO, ID_TEAM, ACTIVO)
SELECT 'Alex', 'Demo', 'Salud', '999000101', DATE '1995-05-15', 'MASCULINO', 'M',
       (SELECT ID FROM SALUDABLEMENTE_OWNER.TEAMS WHERE NAME = 'DEMO-WELLNESS'), TRUE
FROM dual WHERE NOT EXISTS (SELECT 1 FROM SLB_PERSONAL.PERSONA WHERE CELULAR = '999000101');

INSERT INTO SLB_PERSONAL.PERSONA (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, CELULAR, FECHA_NACIMIENTO, SEXO, TALLA_POLO, ID_TEAM, ACTIVO)
SELECT 'Bea', 'Demo', 'Bienestar', '999000102', DATE '1992-08-20', 'FEMENINO', 'S',
       (SELECT ID FROM SALUDABLEMENTE_OWNER.TEAMS WHERE NAME = 'DEMO-WELLNESS'), TRUE
FROM dual WHERE NOT EXISTS (SELECT 1 FROM SLB_PERSONAL.PERSONA WHERE CELULAR = '999000102');

INSERT INTO SLB_PERSONAL.PREFERENCIA_COMUNICACION (CANAL_PREFERIDO, HORARIO_CONTACTO_INICIO, HORARIO_CONTACTO_FIN, ACEPTA_RECORDATORIOS, ID_PERSONA)
SELECT 'EMAIL', TIMESTAMP '2026-09-14 08:00:00', TIMESTAMP '2026-09-14 18:00:00', TRUE, P.ID_PERSONA
FROM SLB_PERSONAL.PERSONA P WHERE P.CELULAR = '999000101'
  AND NOT EXISTS (SELECT 1 FROM SLB_PERSONAL.PREFERENCIA_COMUNICACION X WHERE X.ID_PERSONA = P.ID_PERSONA);

INSERT INTO SLB_PERSONAL.CREDENCIAL_PROGRAMA (CODIGO_QR_HASH, TIPO_CREDENCIAL, FECHA_EMISION, ESTADO, ID_PERSONA)
SELECT 'demo-qr-alex-v1', 'DEMO', TIMESTAMP '2026-09-14 09:00:00', 'ACTIVA', P.ID_PERSONA
FROM SLB_PERSONAL.PERSONA P WHERE P.CELULAR = '999000101'
  AND NOT EXISTS (SELECT 1 FROM SLB_PERSONAL.CREDENCIAL_PROGRAMA X WHERE X.CODIGO_QR_HASH = 'demo-qr-alex-v1');
COMMIT;