-- Synthetic Aptitud Física and Nutricional header-detail examples. Safe to re-run.
INSERT INTO SLB_APTITUDFISICA.CATALOGO_PRUEBA (NOMBRE_PRUEBA, UNIDAD_MEDIDA, DESCRIPCION, ACTIVO)
SELECT 'FLEXIONES_DEMO', 'REPETICIONES', 'Synthetic local demonstration test.', TRUE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM SLB_APTITUDFISICA.CATALOGO_PRUEBA WHERE NOMBRE_PRUEBA = 'FLEXIONES_DEMO');

INSERT INTO SLB_APTITUDFISICA.EVALUACION_APTITUD (ID_PERSONA, FECHA_REGISTRO, PUNTAJE_GLOBAL, DIAGNOSTICO_APTITUD, SINCRONIZADO, FECHA_SINCRONIZACION)
SELECT P.ID_PERSONA, DATE '2026-09-10', 82.50, 'APTO', TRUE, TIMESTAMP '2026-09-10 10:30:00'
FROM SLB_PERSONAL.PERSONA P WHERE P.CELULAR = '999000101'
  AND NOT EXISTS (SELECT 1 FROM SLB_APTITUDFISICA.EVALUACION_APTITUD E WHERE E.ID_PERSONA = P.ID_PERSONA AND E.FECHA_REGISTRO = DATE '2026-09-10' AND E.PUNTAJE_GLOBAL = 82.50 AND E.DIAGNOSTICO_APTITUD = 'APTO');

INSERT INTO SLB_APTITUDFISICA.DETALLE_PRUEBA_FISICA (VALOR_OBTENIDO, PUNTAJE_PARCIAL, ID_EVALUACION_APTITUD, ID_PRUEBA)
SELECT 28.00, 82.50, E.ID_EVALUACION_APTITUD, C.ID_PRUEBA
FROM SLB_APTITUDFISICA.EVALUACION_APTITUD E
JOIN SLB_PERSONAL.PERSONA P ON P.ID_PERSONA = E.ID_PERSONA
CROSS JOIN SLB_APTITUDFISICA.CATALOGO_PRUEBA C
WHERE P.CELULAR = '999000101' AND E.FECHA_REGISTRO = DATE '2026-09-10' AND E.PUNTAJE_GLOBAL = 82.50 AND E.DIAGNOSTICO_APTITUD = 'APTO' AND C.NOMBRE_PRUEBA = 'FLEXIONES_DEMO'
  AND NOT EXISTS (SELECT 1 FROM SLB_APTITUDFISICA.DETALLE_PRUEBA_FISICA D WHERE D.ID_EVALUACION_APTITUD = E.ID_EVALUACION_APTITUD AND D.ID_PRUEBA = C.ID_PRUEBA);

INSERT INTO SLB_NUTRICIONAL.EVALUACION_NUTRICIONAL (ID_PERSONA, FECHA_EVALUACION, PERIODO_SEMESTRAL, ESTADO_EVALUACION, OBSERVACIONES)
SELECT P.ID_PERSONA, DATE '2026-09-11', '2026-II', 'COMPLETADA', 'Synthetic demo evaluation.'
FROM SLB_PERSONAL.PERSONA P WHERE P.CELULAR = '999000101'
  AND NOT EXISTS (SELECT 1 FROM SLB_NUTRICIONAL.EVALUACION_NUTRICIONAL E WHERE E.ID_PERSONA = P.ID_PERSONA AND E.FECHA_EVALUACION = DATE '2026-09-11' AND E.PERIODO_SEMESTRAL = '2026-II' AND E.ESTADO_EVALUACION = 'COMPLETADA');

INSERT INTO SLB_NUTRICIONAL.DETALLE_ANTROPOMETRICO (ESTATURA_CM, PESO_KG, PERIMETRO_ABDOMINAL_CM, IMC, PORCENTAJE_GRASA, PORCENTAJE_MASA_MUSCULAR, PORCENTAJE_GRASA_VISCERAL, DX_IMC, ID_EVALUACION)
SELECT 172.00, 74.00, 84.00, 25.01, 22.50, 37.00, 8.00, 'SOBREPESO_LEVE', E.ID_EVALUACION
FROM SLB_NUTRICIONAL.EVALUACION_NUTRICIONAL E JOIN SLB_PERSONAL.PERSONA P ON P.ID_PERSONA = E.ID_PERSONA
WHERE P.CELULAR = '999000101' AND E.FECHA_EVALUACION = DATE '2026-09-11' AND E.PERIODO_SEMESTRAL = '2026-II' AND E.ESTADO_EVALUACION = 'COMPLETADA'
  AND NOT EXISTS (SELECT 1 FROM SLB_NUTRICIONAL.DETALLE_ANTROPOMETRICO D WHERE D.ID_EVALUACION = E.ID_EVALUACION);

INSERT INTO SLB_NUTRICIONAL.DETALLE_BIOQUIMICO (GLUCOSA, COLESTEROL, TRIGLICERIDOS, PRESION_SISTOLICA, PRESION_DIASTOLICA, DX_BIOQUIMICO, ARCHIVO_ORIGEN, FECHA_IMPORTACION, ID_EVALUACION)
SELECT 92.00, 175.00, 115.00, 118, 76, 'SIN_HALLAZGOS', 'synthetic-demo.csv', TIMESTAMP '2026-09-11 11:00:00', E.ID_EVALUACION
FROM SLB_NUTRICIONAL.EVALUACION_NUTRICIONAL E JOIN SLB_PERSONAL.PERSONA P ON P.ID_PERSONA = E.ID_PERSONA
WHERE P.CELULAR = '999000101' AND E.FECHA_EVALUACION = DATE '2026-09-11' AND E.PERIODO_SEMESTRAL = '2026-II' AND E.ESTADO_EVALUACION = 'COMPLETADA'
  AND NOT EXISTS (SELECT 1 FROM SLB_NUTRICIONAL.DETALLE_BIOQUIMICO D WHERE D.ID_EVALUACION = E.ID_EVALUACION);
COMMIT;