-- Synthetic Activities/Inscripciones and manually managed Metas. Safe to re-run.
INSERT INTO SALUDABLEMENTE_OWNER.ACTIVIDADES (NOMBRE, FECHA, HORA_INICIO, HORA_FIN, LUGAR, ESTADO, CREADOR_ID)
SELECT 'DEMO Caminata Saludable', DATE '2026-09-01', TIMESTAMP '2026-09-01 09:00:00', TIMESTAMP '2026-09-01 10:00:00', 'Parque demo', 'PROGRAMADA', P.ID_PERSONA
FROM SLB_PERSONAL.PERSONA P WHERE P.CELULAR = '999000101'
  AND NOT EXISTS (SELECT 1 FROM SALUDABLEMENTE_OWNER.ACTIVIDADES A WHERE A.NOMBRE = 'DEMO Caminata Saludable' AND A.FECHA = DATE '2026-09-01' AND A.HORA_INICIO = TIMESTAMP '2026-09-01 09:00:00' AND A.HORA_FIN = TIMESTAMP '2026-09-01 10:00:00' AND A.LUGAR = 'Parque demo' AND A.CREADOR_ID = P.ID_PERSONA);

INSERT INTO SALUDABLEMENTE_OWNER.INSCRIPCIONES (ACTIVIDAD_ID, PERSONA_ID, ESTADO, INSCRITA_EN)
SELECT A.ID, P.ID_PERSONA, 'INSCRITA', TIMESTAMP '2026-08-28 09:15:00'
FROM SALUDABLEMENTE_OWNER.ACTIVIDADES A CROSS JOIN SLB_PERSONAL.PERSONA P
WHERE A.NOMBRE = 'DEMO Caminata Saludable' AND A.FECHA = DATE '2026-09-01' AND A.HORA_INICIO = TIMESTAMP '2026-09-01 09:00:00' AND A.HORA_FIN = TIMESTAMP '2026-09-01 10:00:00' AND A.LUGAR = 'Parque demo' AND A.CREADOR_ID = (SELECT ID_PERSONA FROM SLB_PERSONAL.PERSONA WHERE CELULAR = '999000101') AND P.CELULAR = '999000102'
  AND NOT EXISTS (SELECT 1 FROM SALUDABLEMENTE_OWNER.INSCRIPCIONES I WHERE I.ACTIVIDAD_ID = A.ID AND I.PERSONA_ID = P.ID_PERSONA AND I.ESTADO = 'INSCRITA');

INSERT INTO SALUDABLEMENTE_OWNER.METAS (PERSONA_ID, TIPO_META, DESCRIPCION, VALOR_OBJETIVO, VALOR_ACTUAL, FECHA_INICIO, FECHA_LIMITE, ESTADO)
SELECT P.ID_PERSONA, 'ACTIVIDAD_SEMANAL', 'Complete three healthy activity sessions per week.', 3.00, 1.00, DATE '2026-09-01', DATE '2026-10-31', 'EN_CURSO'
FROM SLB_PERSONAL.PERSONA P WHERE P.CELULAR = '999000101'
  AND NOT EXISTS (SELECT 1 FROM SALUDABLEMENTE_OWNER.METAS M WHERE M.PERSONA_ID = P.ID_PERSONA AND M.TIPO_META = 'ACTIVIDAD_SEMANAL' AND M.DESCRIPCION = 'Complete three healthy activity sessions per week.' AND M.FECHA_INICIO = DATE '2026-09-01' AND M.FECHA_LIMITE = DATE '2026-10-31');
COMMIT;