-- Synthetic Personal Health communication data. Safe to re-run.
INSERT INTO SALUD_PERSONAL.ASISTENCIAS (ID_ACTIVIDAD, ID_PERSONA, FECHA_HORA_MARCADO, METODO, ESTADO, ES_OFFLINE, DISPOSITIVO_UUID)
SELECT A.ID, P.ID_PERSONA, TIMESTAMP '2026-09-01 09:05:00', 'MANUAL', 'PRESENTE', FALSE, 'demo-device-bea'
FROM SALUDABLEMENTE_OWNER.ACTIVIDADES A CROSS JOIN SLB_PERSONAL.PERSONA P
WHERE A.NOMBRE = 'DEMO Caminata Saludable' AND A.FECHA = DATE '2026-09-01' AND A.HORA_INICIO = TIMESTAMP '2026-09-01 09:00:00' AND A.HORA_FIN = TIMESTAMP '2026-09-01 10:00:00' AND A.LUGAR = 'Parque demo' AND A.CREADOR_ID = (SELECT ID_PERSONA FROM SLB_PERSONAL.PERSONA WHERE CELULAR = '999000101') AND P.CELULAR = '999000102'
  AND NOT EXISTS (SELECT 1 FROM SALUD_PERSONAL.ASISTENCIAS X WHERE X.ID_ACTIVIDAD = A.ID AND X.ID_PERSONA = P.ID_PERSONA);

INSERT INTO SALUD_PERSONAL.NOTICIAS (TITULO, CONTENIDO, IMAGEN_URL, FECHA_PUBLICACION, ESTADO, ID_USUARIO_AUTOR)
SELECT 'DEMO: Bienestar semanal', 'Synthetic local news item for Swagger demonstrations.', NULL, TIMESTAMP '2026-09-14 08:30:00', 'PUBLICADA', P.ID_PERSONA
FROM SLB_PERSONAL.PERSONA P WHERE P.CELULAR = '999000101'
  AND NOT EXISTS (SELECT 1 FROM SALUD_PERSONAL.NOTICIAS N WHERE N.TITULO = 'DEMO: Bienestar semanal' AND N.ID_USUARIO_AUTOR = P.ID_PERSONA);

INSERT INTO SALUD_PERSONAL.NOTIFICACIONES (ID_PERSONA, TITULO, MENSAJE, MODULO_ORIGEN, REFERENCIA_ID, LEIDO, FECHA_ENVIO)
SELECT P.ID_PERSONA, 'DEMO activity reminder', 'Synthetic reminder for the scheduled demonstration activity.', 'ACTIVIDADES', A.ID, FALSE, TIMESTAMP '2026-08-28 09:20:00'
FROM SLB_PERSONAL.PERSONA P CROSS JOIN SALUDABLEMENTE_OWNER.ACTIVIDADES A
WHERE P.CELULAR = '999000102' AND A.NOMBRE = 'DEMO Caminata Saludable' AND A.FECHA = DATE '2026-09-01' AND A.HORA_INICIO = TIMESTAMP '2026-09-01 09:00:00' AND A.HORA_FIN = TIMESTAMP '2026-09-01 10:00:00' AND A.LUGAR = 'Parque demo' AND A.CREADOR_ID = (SELECT ID_PERSONA FROM SLB_PERSONAL.PERSONA WHERE CELULAR = '999000101')
  AND NOT EXISTS (SELECT 1 FROM SALUD_PERSONAL.NOTIFICACIONES N WHERE N.ID_PERSONA = P.ID_PERSONA AND N.TITULO = 'DEMO activity reminder' AND N.MODULO_ORIGEN = 'ACTIVIDADES' AND N.REFERENCIA_ID = A.ID);
COMMIT;