-- Synthetic alert and recommendation examples. Safe to re-run.
INSERT INTO SALUD_ALERTA_CLINICA.ALERTA_CLINICA (ID_ALERTA, ID_PERSONA, NOMBRE_PACIENTE, ID_EVALUACION_ORIGEN, NIVEL_SEVERIDAD, SCORE_RIESGO, ESTADO, SNAPSHOT_INMUTABLE, FECHA_GENERACION, FECHA_VENCIMIENTO_SLA, VERSION)
SELECT SYS_GUID(), P.ID_PERSONA, 'Alex Demo Salud', E.ID_EVALUACION, 'MODERADO', 42, 'PENDIENTE', '{"source":"synthetic-demo","indicator":"IMC"}', TIMESTAMP '2026-09-12 08:00:00', TIMESTAMP '2026-09-19 08:00:00', 0
FROM SLB_PERSONAL.PERSONA P JOIN SLB_NUTRICIONAL.EVALUACION_NUTRICIONAL E ON E.ID_PERSONA = P.ID_PERSONA
WHERE P.CELULAR = '999000101' AND E.FECHA_EVALUACION = DATE '2026-09-11' AND E.PERIODO_SEMESTRAL = '2026-II' AND E.ESTADO_EVALUACION = 'COMPLETADA'
  AND NOT EXISTS (SELECT 1 FROM SALUD_ALERTA_CLINICA.ALERTA_CLINICA A WHERE A.ID_PERSONA = P.ID_PERSONA AND A.ID_EVALUACION_ORIGEN = E.ID_EVALUACION AND A.NIVEL_SEVERIDAD = 'MODERADO' AND A.SCORE_RIESGO = 42 AND A.ESTADO = 'PENDIENTE' AND A.FECHA_GENERACION = TIMESTAMP '2026-09-12 08:00:00');

INSERT INTO SALUD_ALERTA_CLINICA.ALERTA_CLINICA_DETALLE (ID_DETALLE, ID_ALERTA, TIPO_INDICADOR, VALOR_MEDIDO, LIMITE_REFERENCIA, PORCENTAJE_DESVIACION, MULTIPLICADOR_REINCIDENCIA)
SELECT SYS_GUID(), A.ID_ALERTA, 'IMC', 25.01, 24.90, 0.44, 1.0
FROM SALUD_ALERTA_CLINICA.ALERTA_CLINICA A
JOIN SLB_PERSONAL.PERSONA P ON P.ID_PERSONA = A.ID_PERSONA
JOIN SLB_NUTRICIONAL.EVALUACION_NUTRICIONAL E ON E.ID_EVALUACION = A.ID_EVALUACION_ORIGEN
WHERE P.CELULAR = '999000101' AND E.FECHA_EVALUACION = DATE '2026-09-11' AND E.PERIODO_SEMESTRAL = '2026-II' AND E.ESTADO_EVALUACION = 'COMPLETADA' AND A.NIVEL_SEVERIDAD = 'MODERADO' AND A.SCORE_RIESGO = 42 AND A.ESTADO = 'PENDIENTE' AND A.FECHA_GENERACION = TIMESTAMP '2026-09-12 08:00:00'
  AND NOT EXISTS (SELECT 1 FROM SALUD_ALERTA_CLINICA.ALERTA_CLINICA_DETALLE D WHERE D.ID_ALERTA = A.ID_ALERTA AND D.TIPO_INDICADOR = 'IMC');

INSERT INTO SALUD_RECOMENDACIONES_IA.RECOMENDACION_IA (ID_RECOMENDACION, ID_PERSONA, ID_EVALUACION, MODELO_IA_USADO, PROMPT_CONTEXTO, SCORE_CONFIANZA_IA, VIGENTE, ESTADO_INFERENCIA, FECHA_GENERACION, LEIDA, TIEMPO_INFERENCIA_MS)
SELECT SYS_GUID(), P.ID_PERSONA, E.ID_EVALUACION, 'DEMO_RULE_BASED', 'Synthetic fixture; not an AI production inference.', 1, 1, 'EXITOSA', TIMESTAMP '2026-09-12 09:00:00', 0, 15
FROM SLB_PERSONAL.PERSONA P JOIN SLB_NUTRICIONAL.EVALUACION_NUTRICIONAL E ON E.ID_PERSONA = P.ID_PERSONA
WHERE P.CELULAR = '999000101' AND E.FECHA_EVALUACION = DATE '2026-09-11' AND E.PERIODO_SEMESTRAL = '2026-II' AND E.ESTADO_EVALUACION = 'COMPLETADA'
  AND NOT EXISTS (SELECT 1 FROM SALUD_RECOMENDACIONES_IA.RECOMENDACION_IA R WHERE R.ID_PERSONA = P.ID_PERSONA AND R.ID_EVALUACION = E.ID_EVALUACION AND R.MODELO_IA_USADO = 'DEMO_RULE_BASED' AND R.SCORE_CONFIANZA_IA = 1 AND R.ESTADO_INFERENCIA = 'EXITOSA' AND R.FECHA_GENERACION = TIMESTAMP '2026-09-12 09:00:00');

INSERT INTO SALUD_RECOMENDACIONES_IA.RECOMENDACION_IA_DETALLE (ID_DETALLE, ID_RECOMENDACION, TIPO_SECCION, CONTENIDO_ESTRUCTURADO, CONTRADICCIONES)
SELECT SYS_GUID(), R.ID_RECOMENDACION, 'EJERCICIO', '{"message":"Walk 30 minutes three times per week."}', NULL
FROM SALUD_RECOMENDACIONES_IA.RECOMENDACION_IA R
JOIN SLB_PERSONAL.PERSONA P ON P.ID_PERSONA = R.ID_PERSONA
JOIN SLB_NUTRICIONAL.EVALUACION_NUTRICIONAL E ON E.ID_EVALUACION = R.ID_EVALUACION
WHERE P.CELULAR = '999000101' AND E.FECHA_EVALUACION = DATE '2026-09-11' AND E.PERIODO_SEMESTRAL = '2026-II' AND E.ESTADO_EVALUACION = 'COMPLETADA' AND R.MODELO_IA_USADO = 'DEMO_RULE_BASED' AND R.SCORE_CONFIANZA_IA = 1 AND R.ESTADO_INFERENCIA = 'EXITOSA' AND R.FECHA_GENERACION = TIMESTAMP '2026-09-12 09:00:00'
  AND NOT EXISTS (SELECT 1 FROM SALUD_RECOMENDACIONES_IA.RECOMENDACION_IA_DETALLE D WHERE D.ID_RECOMENDACION = R.ID_RECOMENDACION AND D.TIPO_SECCION = 'EJERCICIO');
COMMIT;

