-- Synthetic report and export-task fixtures. No webhook is seeded because it requires a secret.
INSERT INTO SALUD_PERFIL_REPORTE.REPORTE_PERSONAL (ID_REPORTE, ID_PERSONA, NOMBRE_COLABORADOR, PERIODO_SEMESTRAL, VERSION_REPORTE, SNAPSHOT_DATOS, RUTA_ALMACENAMIENTO, TIPO_ALMACENAMIENTO, TAMANO_BYTES, HASH_INTEGRIDAD_SHA256, ESTADO_GENERACION, FECHA_GENERACION, GENERADO_POR, VIGENTE)
SELECT SYS_GUID(), P.ID_PERSONA, 'Alex Demo Salud', '2026-II', 1, '{"source":"synthetic-demo"}', '/demo/reports/alex-2026-II.pdf', 'LOCAL', 1024, 'demo-report-hash-alex-2026-II', 'COMPLETADO', TIMESTAMP '2026-09-12 12:00:00', 'DEMO_SEED', 1
FROM SLB_PERSONAL.PERSONA P WHERE P.CELULAR = '999000101'
  AND NOT EXISTS (SELECT 1 FROM SALUD_PERFIL_REPORTE.REPORTE_PERSONAL R WHERE R.ID_PERSONA = P.ID_PERSONA AND R.PERIODO_SEMESTRAL = '2026-II' AND R.GENERADO_POR = 'DEMO_SEED');

INSERT INTO SALUD_PERFIL_REPORTE.COLA_GENERACION_REPORTES (ID_TAREA, ID_PERSONA, PERIODO_SEMESTRAL, FORZAR_REGENERACION, INTENTOS_ACUMULADOS, ESTADO_COLA, FECHA_SOLICITUD, FECHA_ULTIMA_ACTUALIZACION)
SELECT SYS_GUID(), P.ID_PERSONA, '2026-II', 0, 0, 'EN_COLA', TIMESTAMP '2026-09-14 10:00:00', TIMESTAMP '2026-09-14 10:00:00'
FROM SLB_PERSONAL.PERSONA P WHERE P.CELULAR = '999000102'
  AND NOT EXISTS (SELECT 1 FROM SALUD_PERFIL_REPORTE.COLA_GENERACION_REPORTES C WHERE C.ID_PERSONA = P.ID_PERSONA AND C.PERIODO_SEMESTRAL = '2026-II' AND C.ESTADO_COLA = 'EN_COLA');

INSERT INTO SALUD_EXPORTACION.TAREA_EXPORTACION (ID_TAREA, ID_USUARIO_SOLICITANTE, TITULO_LOTE, ESTADO_TAREA, FORMATO_SALIDA, MODO_PRIVACIDAD, PARAMETROS_FILTRO, PORCENTAJE_AVANCE, FASE_ACTUAL, TOTAL_REGISTROS_ESTIMADOS, TOTAL_REGISTROS_PROCESADOS, ESTA_CIFRADO, FECHA_SOLICITUD)
SELECT SYS_GUID(), P.ID_PERSONA, 'DEMO export wellness summary', 'COMPLETADO', 'CSV_TABULAR', 'PSEUDONIMIZADO', '{"source":"synthetic-demo"}', 100, 'FINALIZADO', 2, 2, 'N', TIMESTAMP '2026-09-13 15:00:00'
FROM SLB_PERSONAL.PERSONA P WHERE P.CELULAR = '999000101'
  AND NOT EXISTS (SELECT 1 FROM SALUD_EXPORTACION.TAREA_EXPORTACION T WHERE T.TITULO_LOTE = 'DEMO export wellness summary');
COMMIT;