-- =========================================================================
-- SALUDABLEMENTE - SCRIPT MAESTRO DE INICIALIZACION DE ESQUEMAS Y USUARIOS
-- Base de Datos: Oracle 19c / 21c / 23ai Free (PDB: FREEPDB1)
-- Ejecutar conectado como: SYS AS SYSDBA
-- =========================================================================

-- 1. Creacion de usuarios / esquemas por modulo
CREATE USER SALUD_AUDITORIA IDENTIFIED BY 123456 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER SALUD_EXPORTACION IDENTIFIED BY 123456 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER SALUD_PERFIL_REPORTE IDENTIFIED BY 123456 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER SALUD_ALERTA_CLINICA IDENTIFIED BY 123456 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER SALUD_RECOMENDACIONES_IA IDENTIFIED BY 123456 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER SLB_PERSONAL IDENTIFIED BY 123456 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER SLB_APTITUDFISICA IDENTIFIED BY 123456 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER SLB_NUTRICIONAL IDENTIFIED BY 123456 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- 2. Asignacion de roles y privilegios
GRANT ALL PRIVILEGES TO SALUDABLEMENTE_APP;
GRANT DBA TO SALUDABLEMENTE_APP;
GRANT DBA TO SALUD_AUDITORIA;
GRANT DBA TO SALUD_EXPORTACION;
GRANT DBA TO SALUD_PERFIL_REPORTE;
GRANT DBA TO SALUD_ALERTA_CLINICA;
GRANT DBA TO SALUD_RECOMENDACIONES_IA;
GRANT DBA TO SLB_PERSONAL;
GRANT DBA TO SLB_APTITUDFISICA;
GRANT DBA TO SLB_NUTRICIONAL;

-- 3. Tabla interna de Spring Modulith (Event Publication Registry)
CREATE TABLE SALUDABLEMENTE_APP.EVENT_PUBLICATION (
    ID RAW(16) NOT NULL,
    LISTENER_ID VARCHAR2(255) NOT NULL,
    EVENT_TYPE VARCHAR2(255) NOT NULL,
    SERIALIZED_EVENT VARCHAR2(255) NOT NULL,
    PUBLICATION_DATE TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    COMPLETION_DATE TIMESTAMP(6) WITH TIME ZONE,
    COMPLETION_ATTEMPTS NUMBER(10) NOT NULL,
    LAST_RESUBMISSION_DATE TIMESTAMP(6) WITH TIME ZONE,
    STATUS VARCHAR2(255) CHECK (STATUS IN ('PUBLISHED','PROCESSING','COMPLETED','FAILED','RESUBMITTED')),
    PRIMARY KEY (ID)
);

COMMIT;
