-- Tablas
GRANT SELECT, INSERT, UPDATE, DELETE ON PERSONA TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALERTA_CLINICA TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALERTA_CLINICA_DETALLE TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON CATALOGO_ACCION_CORRECTIVA TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON RESOLUCION_CLINICA TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON DLQ_ALERTAS_FALLIDAS TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUDITORIA_ALERTA TO SALUDABLEMENTE_APP;
-- Vista
GRANT SELECT ON V_BANDEJA_ALERTAS TO SALUDABLEMENTE_APP;
-- Secuencias
GRANT SELECT ON SEQ_ALERTA_CLINICA TO SALUDABLEMENTE_APP;
GRANT SELECT ON SEQ_ALERTA_DETALLE TO SALUDABLEMENTE_APP;
GRANT SELECT ON SEQ_RESOLUCION TO SALUDABLEMENTE_APP;
GRANT SELECT ON SEQ_ACCION_CORRECTIVA TO SALUDABLEMENTE_APP;
GRANT SELECT ON SEQ_DLQ_FALLIDAS TO SALUDABLEMENTE_APP;