CREATE TABLE EVENT_PUBLICATION (
  ID RAW(16) NOT NULL PRIMARY KEY,
  EVENT_TYPE VARCHAR2(512) NOT NULL,
  LISTENER_ID VARCHAR2(512) NOT NULL,
  SERIALIZED_EVENT VARCHAR2(4000) NOT NULL,
  PUBLICATION_DATE TIMESTAMP NOT NULL,
  COMPLETION_DATE TIMESTAMP,
  STATUS VARCHAR2(20),
  COMPLETION_ATTEMPTS NUMBER(10),
  LAST_RESUBMISSION_DATE TIMESTAMP
);
CREATE INDEX EVENT_PUBLICATION_BY_COMPLETION_DATE_IDX ON EVENT_PUBLICATION (COMPLETION_DATE);