-- =====================================================
-- 1. CREAR USUARIO Y ASIGNAR PERMISOS BÁSICOS
-- =====================================================
CREATE USER SALUD_ALERTA_CLINICA IDENTIFIED BY 123456;

GRANT CONNECT, RESOURCE, CREATE SESSION TO SALUD_ALERTA_CLINICA;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO SALUD_ALERTA_CLINICA;
GRANT UNLIMITED TABLESPACE TO SALUD_ALERTA_CLINICA;

ALTER USER SALUD_ALERTA_CLINICA QUOTA UNLIMITED ON USERS;

-- 4. Conectarse como el nuevo usuario
-- CONNECT SALUD_ALERTA_CLINICA/123456;

-- =====================================================
-- 1. CREAR USUARIO Y ASIGNAR PERMISOS BÁSICOS
-- =====================================================
CREATE USER SALUD_ALERTA_CLINICA IDENTIFIED BY 123456;

GRANT CONNECT, RESOURCE, CREATE SESSION TO SALUD_ALERTA_CLINICA;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO SALUD_ALERTA_CLINICA;
GRANT UNLIMITED TABLESPACE TO SALUD_ALERTA_CLINICA;

ALTER USER SALUD_ALERTA_CLINICA QUOTA UNLIMITED ON USERS;

-- =====================================================
-- 2. CONECTARSE COMO EL USUARIO CREADO
-- =====================================================
-- CONNECT SALUD_ALERTA_CLINICA/123456;

-- =====================================================
-- 3. CREAR SECUENCIAS
-- =====================================================
CREATE SEQUENCE SEQ_ALERTA_CLINICA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERTA_DETALLE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESOLUCION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ACCION_CORRECTIVA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DLQ_FALLIDAS START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 4. CREAR TABLA PERSONA
-- =====================================================
CREATE TABLE PERSONA (
    ID_PERSONA NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    SEXO CHAR(1) NOT NULL CHECK (SEXO IN ('M', 'F')),
    AREA_TRABAJO VARCHAR2(100),
    EMAIL VARCHAR2(100),
    TELEFONO VARCHAR2(20)
);

-- Insertar datos de ejemplo
INSERT INTO PERSONA (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, AREA_TRABAJO, EMAIL)
VALUES (1, 'Carlos', 'Mendoza Quispe', TO_DATE('1980-05-15', 'YYYY-MM-DD'), 'M', 'Mantenimiento', 'carlos.mendoza@empresa.com');

INSERT INTO PERSONA (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, AREA_TRABAJO, EMAIL)
VALUES (2, 'Maria', 'Lopez Torres', TO_DATE('1990-08-20', 'YYYY-MM-DD'), 'F', 'Administracion', 'maria.lopez@empresa.com');

INSERT INTO PERSONA (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, AREA_TRABAJO, EMAIL)
VALUES (3, 'Juan', 'Perez Gomez', TO_DATE('1985-12-10', 'YYYY-MM-DD'), 'M', 'Operaciones', 'juan.perez@empresa.com');

-- =====================================================
-- 5. CREAR TABLA ALERTA_CLINICA
-- =====================================================
CREATE TABLE ALERTA_CLINICA (
    ID_ALERTA RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ID_PERSONA NUMBER(10) NOT NULL,
    ID_EVALUACION_ORIGEN NUMBER(10),
    NIVEL_SEVERIDAD VARCHAR2(20) NOT NULL,
    SCORE_RIESGO NUMBER(5),
    ESTADO VARCHAR2(20) NOT NULL,
    SNAPSHOT_INMUTABLE CLOB,
    FECHA_GENERACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_VENCIMIENTO_SLA TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0,
    CONSTRAINT FK_ALERTA_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID_PERSONA),
    CONSTRAINT CK_ALERTA_SEVERIDAD CHECK (NIVEL_SEVERIDAD IN ('LEVE', 'MODERADO', 'CRITICO')),
    CONSTRAINT CK_ALERTA_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'EN_REVISION', 'ATENDIDA', 'DESESTIMADA', 'VENCIDO'))
);

-- Índices
CREATE INDEX IDX_ALERTA_PERSONA_ESTADO ON ALERTA_CLINICA(ID_PERSONA, ESTADO);
CREATE INDEX IDX_ALERTA_FECHA_VENCIMIENTO ON ALERTA_CLINICA(FECHA_VENCIMIENTO_SLA);
CREATE INDEX IDX_ALERTA_SEVERIDAD_ESTADO ON ALERTA_CLINICA(NIVEL_SEVERIDAD, ESTADO);
CREATE INDEX IDX_ALERTA_FECHA_GENERACION ON ALERTA_CLINICA(FECHA_GENERACION);

-- =====================================================
-- 6. CREAR TABLA ALERTA_CLINICA_DETALLE
-- =====================================================
CREATE TABLE ALERTA_CLINICA_DETALLE (
    ID_DETALLE RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ID_ALERTA RAW(16) NOT NULL,
    TIPO_INDICADOR VARCHAR2(40) NOT NULL,
    VALOR_MEDIDO NUMBER(10,2) NOT NULL,
    LIMITE_REFERENCIA NUMBER(10,2) NOT NULL,
    PORCENTAJE_DESVIACION NUMBER(5,2),
    MULTIPLICADOR_REINCIDENCIA NUMBER(3,1) DEFAULT 1.0,
    CONSTRAINT FK_DETALLE_ALERTA FOREIGN KEY (ID_ALERTA) REFERENCES ALERTA_CLINICA(ID_ALERTA) ON DELETE CASCADE
);

CREATE INDEX IDX_DETALLE_TIPO_INDICADOR ON ALERTA_CLINICA_DETALLE(TIPO_INDICADOR);
CREATE INDEX IDX_DETALLE_ALERTA ON ALERTA_CLINICA_DETALLE(ID_ALERTA);

-- =====================================================
-- 7. CREAR TABLA CATALOGO_ACCION_CORRECTIVA (CON VARCHAR2)
-- =====================================================
CREATE TABLE CATALOGO_ACCION_CORRECTIVA (
    ID_ACCION NUMBER(10) PRIMARY KEY,
    CODIGO_TIPIFICADO VARCHAR2(40) UNIQUE NOT NULL,
    DESCRIPCION VARCHAR2(150) NOT NULL,
    REQUIERE_SEGUIMIENTO VARCHAR2(1) DEFAULT 'N' CHECK (REQUIERE_SEGUIMIENTO IN ('S', 'N'))
);

-- Insertar catálogo inicial
INSERT INTO CATALOGO_ACCION_CORRECTIVA (ID_ACCION, CODIGO_TIPIFICADO, DESCRIPCION, REQUIERE_SEGUIMIENTO)
VALUES (SEQ_ACCION_CORRECTIVA.NEXTVAL, 'AJUSTE_DIETA', 'Readecuación de plan nutricional y control glucémico', 'S');

INSERT INTO CATALOGO_ACCION_CORRECTIVA (ID_ACCION, CODIGO_TIPIFICADO, DESCRIPCION, REQUIERE_SEGUIMIENTO)
VALUES (SEQ_ACCION_CORRECTIVA.NEXTVAL, 'DERIVACION_EXTERNA', 'Derivación con médico especialista de la EPS', 'S');

INSERT INTO CATALOGO_ACCION_CORRECTIVA (ID_ACCION, CODIGO_TIPIFICADO, DESCRIPCION, REQUIERE_SEGUIMIENTO)
VALUES (SEQ_ACCION_CORRECTIVA.NEXTVAL, 'CONSEJERIA_PREVENTIVA', 'Sesión de orientación sobre hábitos saludables', 'N');

INSERT INTO CATALOGO_ACCION_CORRECTIVA (ID_ACCION, CODIGO_TIPIFICADO, DESCRIPCION, REQUIERE_SEGUIMIENTO)
VALUES (SEQ_ACCION_CORRECTIVA.NEXTVAL, 'PLAN_EJERCICIO', 'Plan de ejercicios supervisado por kinesiólogo', 'S');

INSERT INTO CATALOGO_ACCION_CORRECTIVA (ID_ACCION, CODIGO_TIPIFICADO, DESCRIPCION, REQUIERE_SEGUIMIENTO)
VALUES (SEQ_ACCION_CORRECTIVA.NEXTVAL, 'CONTROL_PESO', 'Programa de control de peso y seguimiento nutricional', 'S');

-- =====================================================
-- 8. CREAR TABLA RESOLUCION_CLINICA
-- =====================================================
CREATE TABLE RESOLUCION_CLINICA (
    ID_RESOLUCION RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ID_ALERTA RAW(16) UNIQUE NOT NULL,
    ID_USUARIO_EVALUADOR NUMBER(10) NOT NULL,
    ID_ACCION_CORRECTIVA NUMBER(10),
    MOTIVO_DESESTIMACION VARCHAR2(100),
    OBSERVACIONES_CLINICAS CLOB,
    FECHA_ATENCION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_RESOLUCION_ALERTA FOREIGN KEY (ID_ALERTA) REFERENCES ALERTA_CLINICA(ID_ALERTA),
    CONSTRAINT FK_RESOLUCION_ACCION FOREIGN KEY (ID_ACCION_CORRECTIVA) REFERENCES CATALOGO_ACCION_CORRECTIVA(ID_ACCION)
);

CREATE INDEX IDX_RESOLUCION_ALERTA ON RESOLUCION_CLINICA(ID_ALERTA);
CREATE INDEX IDX_RESOLUCION_EVALUADOR ON RESOLUCION_CLINICA(ID_USUARIO_EVALUADOR);
CREATE INDEX IDX_RESOLUCION_FECHA_ATENCION ON RESOLUCION_CLINICA(FECHA_ATENCION);

-- =====================================================
-- 9. CREAR TABLA DLQ_ALERTAS_FALLIDAS
-- =====================================================
CREATE TABLE DLQ_ALERTAS_FALLIDAS (
    ID_FALLO RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    PAYLOAD_EVENTO CLOB NOT NULL,
    TIPO_EXCEPCION VARCHAR2(150) NOT NULL,
    CONTADOR_REINTENTOS NUMBER(5) DEFAULT 0,
    ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE',
    FECHA_FALLO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ULTIMO_INTENTO TIMESTAMP,
    MENSAJE_ERROR VARCHAR2(500)
);

CREATE INDEX IDX_DLQ_ESTADO ON DLQ_ALERTAS_FALLIDAS(ESTADO);
CREATE INDEX IDX_DLQ_FECHA_FALLO ON DLQ_ALERTAS_FALLIDAS(FECHA_FALLO);
CREATE INDEX IDX_DLQ_CONTADOR ON DLQ_ALERTAS_FALLIDAS(CONTADOR_REINTENTOS);

-- =====================================================
-- 10. CREAR TABLA AUDITORIA_ALERTA
-- =====================================================
CREATE TABLE AUDITORIA_ALERTA (
    ID_AUDITORIA RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ID_ALERTA RAW(16) NOT NULL,
    CAMPO_MODIFICADO VARCHAR2(50),
    VALOR_ANTERIOR VARCHAR2(200),
    VALOR_NUEVO VARCHAR2(200),
    ID_USUARIO NUMBER(10),
    FECHA_CAMBIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACCION VARCHAR2(20)
);

CREATE INDEX IDX_AUDITORIA_ALERTA ON AUDITORIA_ALERTA(ID_ALERTA);

-- =====================================================
-- 11. CREAR VISTA BANDEJA
-- =====================================================
CREATE OR REPLACE VIEW V_BANDEJA_ALERTAS AS
SELECT 
    a.ID_ALERTA,
    p.NOMBRE || ' ' || p.APELLIDO AS NOMBRE_PACIENTE,
    p.AREA_TRABAJO,
    a.NIVEL_SEVERIDAD,
    a.ESTADO,
    a.FECHA_GENERACION,
    a.FECHA_VENCIMIENTO_SLA,
    EXTRACT(HOUR FROM (a.FECHA_VENCIMIENTO_SLA - SYSTIMESTAMP)) AS HORAS_SLA_RESTANTES,
    (SELECT LISTAGG(d.TIPO_INDICADOR, ', ') WITHIN GROUP (ORDER BY d.TIPO_INDICADOR) 
     FROM ALERTA_CLINICA_DETALLE d 
     WHERE d.ID_ALERTA = a.ID_ALERTA) AS INDICADORES_AFECTADOS,
    CASE 
        WHEN a.FECHA_VENCIMIENTO_SLA < SYSTIMESTAMP AND a.ESTADO IN ('PENDIENTE', 'EN_REVISION') 
        THEN 'VENCIDO' 
        ELSE 'ACTIVO' 
    END AS ESTADO_SLA
FROM ALERTA_CLINICA a
INNER JOIN PERSONA p ON a.ID_PERSONA = p.ID_PERSONA;

-- =====================================================
-- 12. CREAR TRIGGERS
-- =====================================================
CREATE OR REPLACE TRIGGER TRG_ALERTA_SLA
BEFORE INSERT ON ALERTA_CLINICA
FOR EACH ROW
BEGIN
    IF :NEW.NIVEL_SEVERIDAD = 'CRITICO' THEN
        :NEW.FECHA_VENCIMIENTO_SLA := SYSTIMESTAMP + INTERVAL '72' HOUR;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ALERTA_AUDITORIA
BEFORE UPDATE ON ALERTA_CLINICA
FOR EACH ROW
BEGIN
    IF :OLD.ESTADO != :NEW.ESTADO THEN
        INSERT INTO AUDITORIA_ALERTA (ID_ALERTA, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, ACCION)
        VALUES (:NEW.ID_ALERTA, 'ESTADO', :OLD.ESTADO, :NEW.ESTADO, 'CAMBIAR_ESTADO');
    END IF;
END;
/

-- =====================================================
-- 13. CREAR USUARIO DE APLICACIÓN Y ASIGNAR PERMISOS
-- =====================================================
-- Conectarse como SYS o SYSTEM para crear el usuario de aplicación
-- CREATE USER SALUDABLEMENTE_APP IDENTIFIED BY 123456;
-- GRANT CONNECT, CREATE SESSION TO SALUDABLEMENTE_APP;

-- ASIGNAR PERMISOS DE LECTURA/ESCRITURA (Ejecutar como SYS/SYSTEM)
GRANT SELECT, INSERT, UPDATE, DELETE ON SALUD_ALERTA_CLINICA.PERSONA TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SALUD_ALERTA_CLINICA.ALERTA_CLINICA TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SALUD_ALERTA_CLINICA.ALERTA_CLINICA_DETALLE TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SALUD_ALERTA_CLINICA.CATALOGO_ACCION_CORRECTIVA TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SALUD_ALERTA_CLINICA.RESOLUCION_CLINICA TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SALUD_ALERTA_CLINICA.DLQ_ALERTAS_FALLIDAS TO SALUDABLEMENTE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SALUD_ALERTA_CLINICA.AUDITORIA_ALERTA TO SALUDABLEMENTE_APP;

-- Permisos para la vista
GRANT SELECT ON SALUD_ALERTA_CLINICA.V_BANDEJA_ALERTAS TO SALUDABLEMENTE_APP;

-- Permisos para secuencias
GRANT SELECT ON SALUD_ALERTA_CLINICA.SEQ_ALERTA_CLINICA TO SALUDABLEMENTE_APP;
GRANT SELECT ON SALUD_ALERTA_CLINICA.SEQ_ALERTA_DETALLE TO SALUDABLEMENTE_APP;
GRANT SELECT ON SALUD_ALERTA_CLINICA.SEQ_RESOLUCION TO SALUDABLEMENTE_APP;
GRANT SELECT ON SALUD_ALERTA_CLINICA.SEQ_ACCION_CORRECTIVA TO SALUDABLEMENTE_APP;
GRANT SELECT ON SALUD_ALERTA_CLINICA.SEQ_DLQ_FALLIDAS TO SALUDABLEMENTE_APP;

-- Permisos para ejecutar triggers (opcional)
GRANT EXECUTE ON SALUD_ALERTA_CLINICA.TRG_ALERTA_SLA TO SALUDABLEMENTE_APP;
GRANT EXECUTE ON SALUD_ALERTA_CLINICA.TRG_ALERTA_AUDITORIA TO SALUDABLEMENTE_APP;

COMMIT;