-- S01_01_esquemas.sql - Saludablemente (LP2 S1)
-- Ejecutar conectado como SYSTEM

CREATE USER SALUD_PERSONAL IDENTIFIED BY 123456;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO SALUD_PERSONAL;
GRANT UNLIMITED TABLESPACE TO SALUD_PERSONAL;
