spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:oracle:thin:@localhost:1522/SALUDPDB
    username: SALUDABLEMENTE_APP
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    pe.edu.upeu.saludablemente: INFO
