package pe.edu.upeu.saludablemente.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Provides presentation metadata for the OpenAPI document generated by Springdoc.
 */
@Configuration(proxyBeanMethods = false)
public class OpenApiConfig {

    @Bean
    OpenAPI saludablementeOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("Saludablemente API")
                        .version("1.0.0")
                        .description("REST API for Saludablemente wellness management modules."));
    }
}
